// <auto-generated />
using System;
using BurgerPOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BurgerPOS.Infrastructure.Migrations
{
    [DbContext(typeof(BurgerPosDbContext))]
    [Migration("20260625022458_AgregaNumeroEnvio")]
    partial class AgregaNumeroEnvio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("folio_orden_seq");

            modelBuilder.HasSequence<int>("folio_venta_seq");

            modelBuilder.Entity("BurgerPOS.Domain.Administracion.Entities.BitacoraEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidad_afectada");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<string>("IpOrigen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_origen");

                    b.Property<int?>("RolOperativoDeclarado")
                        .HasColumnType("integer")
                        .HasColumnName("rol_operativo_declarado");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id")
                        .HasName("pk_bitacora_eventos");

                    b.ToTable("bitacora_eventos", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.CampaniaDescuento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Alcance")
                        .HasColumnType("integer")
                        .HasColumnName("alcance");

                    b.Property<string>("DiasSemana")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dias_semana");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_campanias_descuento");

                    b.ToTable("campanias_descuento", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("OrdenVisual")
                        .HasColumnType("integer")
                        .HasColumnName("orden_visual");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.Combo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioEspecial")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("precio_especial");

                    b.HasKey("Id")
                        .HasName("pk_combos");

                    b.ToTable("combos", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.ComponenteCombo", b =>
                {
                    b.Property<Guid>("ComboId")
                        .HasColumnType("uuid")
                        .HasColumnName("combo_id");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.HasKey("ComboId", "ProductoId")
                        .HasName("pk_componentes_combo");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_componentes_combo_producto_id");

                    b.ToTable("componentes_combo", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.DatosEstablecimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<string>("LeyendaTicket")
                        .HasColumnType("text")
                        .HasColumnName("leyenda_ticket");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("Rfc")
                        .HasColumnType("text")
                        .HasColumnName("rfc");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_datos_establecimiento");

                    b.ToTable("datos_establecimiento", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.LineaReceta", b =>
                {
                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uuid")
                        .HasColumnName("insumo_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("cantidad");

                    b.HasKey("RecetaId", "InsumoId")
                        .HasName("pk_lineas_receta");

                    b.ToTable("lineas_receta", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.Modificador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DeltaPrecio")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("delta_precio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_modificadores");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_modificadores_producto_id");

                    b.ToTable("modificadores", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("precio_base");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_productos_categoria_id");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_recetas");

                    b.HasIndex("ProductoId")
                        .IsUnique()
                        .HasDatabaseName("ix_recetas_producto_id");

                    b.ToTable("recetas", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Cobro.Entities.DescuentoAplicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaniaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campania_id");

                    b.Property<decimal>("MontoCalculado")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monto_calculado");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("pk_descuentos_aplicados");

                    b.HasIndex("VentaId")
                        .IsUnique()
                        .HasDatabaseName("ix_descuentos_aplicados_venta_id");

                    b.ToTable("descuentos_aplicados", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Cobro.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Cambio")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cambio");

                    b.Property<decimal?>("ComisionBancaria")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("comision_bancaria");

                    b.Property<int>("Metodo")
                        .HasColumnType("integer")
                        .HasColumnName("metodo");

                    b.Property<decimal?>("MontoRecibido")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monto_recibido");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("pk_pagos");

                    b.HasIndex("VentaId")
                        .IsUnique()
                        .HasDatabaseName("ix_pagos_venta_id");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Cobro.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContenidoSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido_snapshot");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("VentaId")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_venta_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Cobro.Entities.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Anulada")
                        .HasColumnType("boolean")
                        .HasColumnName("anulada");

                    b.Property<decimal>("BaseGravable")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("base_gravable");

                    b.Property<DateTime>("FechaCobro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cobro");

                    b.Property<int>("Folio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("folio")
                        .HasDefaultValueSql("nextval('folio_venta_seq')");

                    b.Property<decimal>("Iva")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("iva");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monto_descuento");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_id");

                    b.Property<Guid>("OrdenId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_id");

                    b.Property<decimal>("Propina")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("propina");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total");

                    b.Property<Guid>("TurnoCajaId")
                        .HasColumnType("uuid")
                        .HasColumnName("turno_caja_id");

                    b.HasKey("Id")
                        .HasName("pk_ventas");

                    b.HasIndex("Folio")
                        .IsUnique()
                        .HasDatabaseName("ix_ventas_folio");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Identidad.Entities.SesionUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<int>("RolOperativo")
                        .HasColumnType("integer")
                        .HasColumnName("rol_operativo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_sesiones_usuario");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_sesiones_usuario_usuario_id");

                    b.ToTable("sesiones_usuario", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Identidad.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Inventario.Entities.AjusteSaldo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<decimal>("CantidadAnterior")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("cantidad_anterior");

                    b.Property<decimal>("CantidadNueva")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("cantidad_nueva");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("diferencia");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uuid")
                        .HasColumnName("insumo_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.HasKey("Id")
                        .HasName("pk_ajustes_saldo");

                    b.HasIndex("InsumoId")
                        .HasDatabaseName("ix_ajustes_saldo_insumo_id");

                    b.ToTable("ajustes_saldo", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Inventario.Entities.EntradaInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("cantidad");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("costo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uuid")
                        .HasColumnName("insumo_id");

                    b.Property<string>("Proveedor")
                        .HasColumnType("text")
                        .HasColumnName("proveedor");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_entradas_inventario");

                    b.HasIndex("InsumoId")
                        .HasDatabaseName("ix_entradas_inventario_insumo_id");

                    b.ToTable("entradas_inventario", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Inventario.Entities.Insumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<decimal>("NivelAlerta")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("nivel_alerta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("saldo_actual");

                    b.Property<int>("Unidad")
                        .HasColumnType("integer")
                        .HasColumnName("unidad");

                    b.HasKey("Id")
                        .HasName("pk_insumos");

                    b.ToTable("insumos", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Inventario.Entities.Merma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uuid")
                        .HasColumnName("insumo_id");

                    b.Property<int>("Motivo")
                        .HasColumnType("integer")
                        .HasColumnName("motivo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_mermas");

                    b.HasIndex("InsumoId")
                        .HasDatabaseName("ix_mermas_insumo_id");

                    b.ToTable("mermas", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Ordenes.Entities.LineaModificador", b =>
                {
                    b.Property<Guid>("LineaOrdenId")
                        .HasColumnType("uuid")
                        .HasColumnName("linea_orden_id");

                    b.Property<Guid>("ModificadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificador_id");

                    b.Property<decimal>("DeltaAplicado")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("delta_aplicado");

                    b.HasKey("LineaOrdenId", "ModificadorId")
                        .HasName("pk_lineas_modificador");

                    b.ToTable("lineas_modificador", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Ordenes.Entities.LineaOrden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid?>("ComboId")
                        .HasColumnType("uuid")
                        .HasColumnName("combo_id");

                    b.Property<string>("NotaLibre")
                        .HasColumnType("text")
                        .HasColumnName("nota_libre");

                    b.Property<int>("NumeroEnvio")
                        .HasColumnType("integer")
                        .HasColumnName("numero_envio");

                    b.Property<Guid>("OrdenId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("precio_unitario");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_lineas_orden");

                    b.HasIndex("OrdenId")
                        .HasDatabaseName("ix_lineas_orden_orden_id");

                    b.ToTable("lineas_orden", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Ordenes.Entities.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_mesas");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_mesas_numero");

                    b.ToTable("mesas", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Ordenes.Entities.Orden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("FolioOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("folio_orden")
                        .HasDefaultValueSql("nextval('folio_orden_seq')");

                    b.Property<Guid?>("MesaId")
                        .HasColumnType("uuid")
                        .HasColumnName("mesa_id");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer")
                        .HasColumnName("modalidad");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("subtotal");

                    b.Property<int>("TotalEnvios")
                        .HasColumnType("integer")
                        .HasColumnName("total_envios");

                    b.HasKey("Id")
                        .HasName("pk_ordenes");

                    b.HasIndex("MesaId")
                        .HasDatabaseName("ix_ordenes_mesa_id");

                    b.ToTable("ordenes", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Turno.Entities.TurnoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Diferencia")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("diferencia");

                    b.Property<decimal?>("EfectivoContado")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("efectivo_contado");

                    b.Property<decimal>("EfectivoEsperado")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("efectivo_esperado");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<decimal>("FondoInicial")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("fondo_inicial");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("OperadorAperturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_apertura_id");

                    b.Property<Guid?>("OperadorCierreId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_cierre_id");

                    b.HasKey("Id")
                        .HasName("pk_turnos_caja");

                    b.ToTable("turnos_caja", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_rol_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_rol_claims_role_id");

                    b.ToTable("rol_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuario_claims_user_id");

                    b.ToTable("usuario_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_usuario_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuario_logins_user_id");

                    b.ToTable("usuario_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_usuario_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_usuario_roles_role_id");

                    b.ToTable("usuario_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_usuario_tokens");

                    b.ToTable("usuario_tokens", (string)null);
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.ComponenteCombo", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Catalogo.Entities.Combo", "Combo")
                        .WithMany("Componentes")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_componentes_combo_combos_combo_id");

                    b.HasOne("BurgerPOS.Domain.Catalogo.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_componentes_combo_productos_producto_id");

                    b.Navigation("Combo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.LineaReceta", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Catalogo.Entities.Receta", null)
                        .WithMany("Lineas")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineas_receta_recetas_receta_id");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.Modificador", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Catalogo.Entities.Producto", "Producto")
                        .WithMany("Modificadores")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modificadores_productos_producto_id");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.Producto", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Catalogo.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.Receta", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Catalogo.Entities.Producto", "Producto")
                        .WithOne("Receta")
                        .HasForeignKey("BurgerPOS.Domain.Catalogo.Entities.Receta", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recetas_productos_producto_id");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Cobro.Entities.DescuentoAplicado", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Cobro.Entities.Venta", null)
                        .WithOne("DescuentoAplicado")
                        .HasForeignKey("BurgerPOS.Domain.Cobro.Entities.DescuentoAplicado", "VentaId")
                        .HasConstraintName("fk_descuentos_aplicados_ventas_venta_id");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Cobro.Entities.Pago", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Cobro.Entities.Venta", "Venta")
                        .WithOne("Pago")
                        .HasForeignKey("BurgerPOS.Domain.Cobro.Entities.Pago", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_ventas_venta_id");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Cobro.Entities.Ticket", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Cobro.Entities.Venta", "Venta")
                        .WithOne("Ticket")
                        .HasForeignKey("BurgerPOS.Domain.Cobro.Entities.Ticket", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_ventas_venta_id");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Identidad.Entities.SesionUsuario", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Identidad.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sesiones_usuario_usuario_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Inventario.Entities.AjusteSaldo", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Inventario.Entities.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ajustes_saldo_insumos_insumo_id");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Inventario.Entities.EntradaInventario", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Inventario.Entities.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entradas_inventario_insumos_insumo_id");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Inventario.Entities.Merma", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Inventario.Entities.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mermas_insumos_insumo_id");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Ordenes.Entities.LineaModificador", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Ordenes.Entities.LineaOrden", "LineaOrden")
                        .WithMany("Modificadores")
                        .HasForeignKey("LineaOrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineas_modificador_lineas_orden_linea_orden_id");

                    b.Navigation("LineaOrden");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Ordenes.Entities.LineaOrden", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Ordenes.Entities.Orden", null)
                        .WithMany("Lineas")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineas_orden_ordenes_orden_id");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Ordenes.Entities.Orden", b =>
                {
                    b.HasOne("BurgerPOS.Domain.Ordenes.Entities.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .HasConstraintName("fk_ordenes_mesas_mesa_id");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rol_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BurgerPOS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_claims_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BurgerPOS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_logins_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_roles_roles_role_id");

                    b.HasOne("BurgerPOS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_roles_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BurgerPOS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_tokens_usuarios_user_id");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.Combo", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.Producto", b =>
                {
                    b.Navigation("Modificadores");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Catalogo.Entities.Receta", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Cobro.Entities.Venta", b =>
                {
                    b.Navigation("DescuentoAplicado");

                    b.Navigation("Pago");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Ordenes.Entities.LineaOrden", b =>
                {
                    b.Navigation("Modificadores");
                });

            modelBuilder.Entity("BurgerPOS.Domain.Ordenes.Entities.Orden", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
